type: PolicyGradientAgent
args:
  gamma: 0.98
  lr: 0.001
  epochs: 2000
  max_steps: 1000
policy:
  net:
    -
      type: mlp
      args:
        input_dim: 24
        h_dims: [128, 192, 64, 32, 4]
  sampler:
    type: Gaussian
    args:
      act_dim: 4