type: PolicyGradientAgent
args:
  gamma: 0.98
  lr: 0.001
  epochs: 200
  max_steps: 1000
policy:
  net:
    -
      type: mlp
      args:
        input_dim: 4
        h_dims: [32, 16, 2]
  sampler:
    type: Categorical
    args:
      temperature: 1.0