type: PolicyGradientAgent
args:
  gamma: 0.98
  lr: 0.001
  epochs: 400
  max_steps: 500
policy:
  net:
    -
      type: mlp
      args:
        input_dim: 8
        h_dims: [64, 32, 16, 2]
  sampler:
    type: Gaussian
    args:
      act_dim: 2