type: PolicyGradientAgent
args:
  gamma: 0.99
  lr: 0.001
  epochs: 300
  max_steps: 1000
policy:
  net:
    -
      type: mlp
      args:
        input_dim: 2
        h_dims: [32, 16, 3]
  sampler:
    type: Categorical
    args:
      temperature: 1.0