type: PolicyGradientAgent
args:
  gamma: 0.99
  lr: 0.001
  epochs: 1000
  max_steps: 500
policy:
  net:
    -
      type: embedding
      args:
        input_dim: 500
        h_dim: 64
    - 
      type: mlp
      args:
        input_dim: 64
        h_dims: [128, 128, 64, 16, 6]
  sampler:
    type: Categorical
    args:
      temperature: 1.0