type: ActorCriticAgent
args:
  gamma: 0.99
  lr: 0.001
  epochs: 200
  max_steps: 500
  arch:
    policy:
      type: mlp
      args:
        input_dim: 8
        h_dims: [64, 32, 16, 4]
    sampler:
      type: Categorical
      args:
        temperature: 1.0
    value:
      type: mlp
      args:
        input_dim: 8
        h_dims: [64, 32, 16, 1]
